// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.gwizards.prcs;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import org.gwizards.prcs.LiveProjectStageTaskDocumentVersion;

privileged aspect LiveProjectStageTaskDocumentVersion_Roo_Jpa_Entity {
    
    declare @type: LiveProjectStageTaskDocumentVersion: @Entity;
    
    declare @type: LiveProjectStageTaskDocumentVersion: @Table(name = "live_project_stage_task_document_version");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "live_project_stage_task_document_version_no", columnDefinition = "INT")
    private Integer LiveProjectStageTaskDocumentVersion.liveProjectStageTaskDocumentVersionNo;
    
    public Integer LiveProjectStageTaskDocumentVersion.getLiveProjectStageTaskDocumentVersionNo() {
        return this.liveProjectStageTaskDocumentVersionNo;
    }
    
    public void LiveProjectStageTaskDocumentVersion.setLiveProjectStageTaskDocumentVersionNo(Integer id) {
        this.liveProjectStageTaskDocumentVersionNo = id;
    }
    
}
