// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.gwizards.prcs;

import org.gwizards.prcs.Sequence;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Sequence_Roo_Configurable {
    
    declare @type: Sequence: @Configurable;
    
}
