// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.gwizards.prcs;

import org.gwizards.prcs.StudentProject;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect StudentProject_Roo_Configurable {
    
    declare @type: StudentProject: @Configurable;
    
}
