// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.gwizards.prcs;

import java.io.Serializable;
import org.gwizards.prcs.StudentProjectReviewPK;

privileged aspect StudentProjectReviewPK_Roo_Serializable {
    
    declare parents: StudentProjectReviewPK implements Serializable;
    
    private static final long StudentProjectReviewPK.serialVersionUID = 1L;
    
}
